/**
 * Define and export events
 */

module.exports = {
  SET_DEFAULT: 'set_default',
  START_UNIT: 'start_unit',
  STOP_UNIT: 'stop_unit',
  RELOAD_UNIT: 'reload_unit',
  RESTART_UNIT: 'restart_unit',
  TRY_RESTART_UNIT: 'try_restart_unit',
  RELOAD_OR_RESTART_UNIT: 'reload_or_restart_unit',
  TRY_RELOAD_OR_RESTART_UNIT: 'try_reload_or_restart_unit',
  POWEROFF: 'poweroff',
  HALT: 'halt',
  REBOOT: 'reboot',
  SUSPEND: 'suspend',
  HIBERNATE: 'hibernate',
  HYBRID_SLEEP: 'hybrid_sleep',
  DAEMON_RELOAD: 'daemon_reload',
  ENABLE_UNIT: 'enable_unit',
  REENABLE: 'reenable',
  DISABLE: 'disable',
  MASK: 'mask',
  UNMASK: 'unmask',
  PRESET: 'preset',
  PRESET_ALL: 'preset_all',
  REVERT: 'revert',
  LINK: 'link',
  ADD_UNIT: 'add_unit',
  EDIT_UNIT: 'edit_unit',
  REMOVE_UNIT: 'remove_unit',
  LOCK_SESSION: 'lock_session',
  UNLOCK_SESSION: 'unlock_session',
  TERMINATE_SESSION: 'terminate_session',
  TERMINATE_USER: 'terminate_user',
  SET_HOSTNAME: 'set_hostname',
  SET_ICON_NAME: 'set_icon_name',
  SET_CHASSIS: 'set_chassis',
  SET_DEPLOYMENT: 'set_deployment',
  SET_LOCATION: 'set_location',
  SET_LOCALE: 'set_locale',
  SET_KEYMAP: 'set_keymap',
  SET_X11_KEYMAP: 'set_x11_keymap',
  UPDATE_BOOT_LOADER: 'update_boot_loader',
  INSTALL_BOOT_LOADER: 'install_boot_loader',
  REMOVE_BOOT_LOADER: 'remove_boot_loader',
  SET_TIMEZONE: 'set_timezone',
  SET_TIME: 'set_time',
  UPLOAD_SAMPLE: 'upload_sample',
  PLAY_AUDIO_SAMPLE: 'play_audio_sample',
  REMOVE_AUDIO_SAMPLE: 'remove_audio_sample',
};
